esphome:
  name: p1-sensor
  platform: ESP8266
#  board: nodemcuv2
  board: d1_mini
  name_add_mac_suffix: false  
  esp8266_restore_from_flash: true

external_components:
  - source:
      type: local
      path: ./components/
    components: [dsmr]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  manual_ip:
    static_ip: 192.168.8.97
    gateway: 192.168.8.1
    subnet: 255.255.255.0

  ap:
    ssid: "p1-sensor"
    password: !secret wifi_password  

api:
   #password: !secret api_password  
#   encryption:
#    key: "K2qZxaca8n+VDFVT/qDS3RDoprBIcEqkPyahMAkb334="

captive_portal:

mqtt:
  broker: 192.168.8.123
  port: 1883  
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: openhab/p1
  discovery: False
  discover_ip: False  
  reboot_timeout: 0s
       
ota:
   platform: esphome  
   password: !secret ota_password

web_server:
  port: 80

safe_mode: 

logger:
  baud_rate: 0
  level: INFO

uart:
  rx_pin:
    number: GPIO3
  baud_rate: 115200
  rx_buffer_size: 3000  

dsmr:  
  max_telegram_length: 3000
  id: dsmr_instance
  crc_check: false
  request_pin: D5
  request_interval: 20s  

sensor:
  - platform: dsmr
#    energy_delivered:
#      name: energy_delivered
#      accuracy_decimals: 3
    energy_delivered_tariff1:
      name: energy_delivered_tariff1
      accuracy_decimals: 3
    energy_delivered_tariff2:
      name: energy_delivered_tariff2
      accuracy_decimals: 3

#    energy_returned:
#      name: energy_returned
#      accuracy_decimals: 3      
    energy_returned_tariff1:
      name: energy_returned_tariff1
      accuracy_decimals: 3
    energy_returned_tariff2:
      name: energy_returned_tariff2
      accuracy_decimals: 3

#    electricity_tariff:
#      name: "Aktuális tarifa"

#    energy_absolute:
#      name: "Összes hatásos energia - vételezett és betáplált"      

    power_delivered:
      name: power_delivered
      device_class: power
      accuracy_decimals: 3
      id: power_delivered
    power_returned:
      name: power_returned
      device_class: power
      accuracy_decimals: 3
      id: power_returned

    power_delivered_l1:
      name: power_delivered_l1
      device_class: power
    power_delivered_l2:
      name: power_delivered_l2 
      device_class: power
    power_delivered_l3:
      name: power_delivered_l3 
      device_class: power
    power_returned_l1:
      name: power_returned_l1
      device_class: power
    power_returned_l2:
      name: power_returned_l2
      device_class: power
    power_returned_l3:
      name: power_returned_l3
      device_class: power

    voltage_l1:
      name: voltage_l1  
    voltage_l2:
      name: voltage_l2
    voltage_l3:
      name: voltage_l3  
    current_l1:
      name: current_l1
    current_l2:
      name: current_l2
    current_l3:
      name: current_l3

#    instantaneous_power_factor:
#      name: "Teljesítménytényező - eredő"
#      device_class: power_factor
#    instantaneous_power_factor_l1:
#      name: "Teljesítménytényező L1"
#      device_class: power_factor
#    instantaneous_power_factor_l2:
#      name: "Teljesítménytényező L2"
#      device_class: power_factor
#    instantaneous_power_factor_l3:
#      name: "Teljesítménytényező L3"
#      device_class: power_factor

#    reactive_power_qi:
#      name: "Pillanatnyi teljesítmény - meddő (QI)"
#      device_class: reactive_power
#    reactive_power_qii:
#      name: "Pillanatnyi teljesítmény - meddő (QII)"
#      device_class: reactive_power
#    reactive_power_qiii:
#      name: "Pillanatnyi teljesítmény - meddő (QIII)"
#      device_class: reactive_power
#    reactive_power_qiv:
#      name: "Pillanatnyi teljesítmény - meddő (QIV)"
#      device_class: reactive_power

#    energy_positive_reactive:
#      name: "Meddő energia - vételezett (+R)"
#    energy_negative_reactive:
#      name: "Meddő energia - betáplált (-R)"
#    reactive_energy_qi:
#      name: "Meddő energia (QI)"
#    reactive_energy_qii:
#      name: "Meddő energia (QII)"
#    reactive_energy_qiii:
#      name: "Meddő energia (QIII)"
#    reactive_energy_qiv:
#      name: "Meddő energia (QIV)"

   # Mérőóra áramkorlátozó felügyeletének beállítási értéke
#    electricity_threshold_l1:
#      name: "Áramkorlátozó felügyelet küszöbértéke L1"
#    electricity_threshold_l2:
#      name: "Áramkorlátozó felügyelet küszöbértéke L2"
#    electricity_threshold_l3:
#      name: "Áramkorlátozó felügyelet küszöbértéke L3"

#    electricity_threshold:
#      name: "Áramkorlátozó küszöbértéke"

  - platform: uptime
    name: "SlimmeLezer üzemidő"
    device_class: duration

  - platform: wifi_signal
    name: "P1 Wi-Fi jel"
    update_interval: 60s    

text_sensor:
  - platform: dsmr
    identification:
      name: "DSMR Identification"
    timestamp:
      name: "Timestamp"
#    message_short:
#      name: "Message short"       
    message_long:
      name: "Message long"
#    breaker_status:
#      name: "Megszakító státusz"
#    breaker_status_b:
#      name: "Megszakító státusz"

